### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by mdanko2000** [infostreams/excel-merge#12]
1. SharedStrings.php
	public function merge($zip_dir = null) {
.....
		$target->documentElement->setAttribute('uniqueCount',count($shared_strings)); // <-- update uniqueCount
		$target->save($target_filename);

		return $mapping;
	}

2. Styles.php
styles from the first sheet are lost
***** Styles_new.php
                                        $new_id = count($defined_styles);
                                        $defined_styles[$new_id] = array(   // <-- add new element
                                                "node" => $style,
***** STYLES_OLD.PHP
                                        $new_id = count($defined_styles);
                                        $defined_styles[$id] = array(  // <-- owerwrite exist element
                                                "node" => $style,
*****

**Comment by mdanko2000** [comment]
3. remaping default cells style for sheets
worksheet.php
.................
		$this->remapStyles($sheet, $styles_mapping);
		$this->remapConditionalStyles($sheet, $conditional_styles_mapping);
		$this->remapColsStyles($sheet, $styles_mapping);  // <--- call remaping
.......................



	protected function remapColsStyles($sheet, $mapping) {
		$this->doRemapping($sheet, "//m:col[@style]", "style", $mapping);
	}

**Comment by infostreams** [comment]
I'm sorry, but it's very hard to understand what you mean here. I understand that you've found some errors and want to show me how you fixed them. I want to include your changes to the repository so that everyone has these fixes. Can you make these changes on GitHub instead of as a comment? 

You can do this by going to the file you want to change, and clicking on the little pencil icon there. This will create a fork and allow you to edit the file.

To change SharedStrings.php, go here https://github.com/infostreams/excel-merge/blob/master/Tasks/SharedStrings.php
For Styles.php, go here https://github.com/infostreams/excel-merge/blob/master/Tasks/Styles.php
For Worksheet.php, go here https://github.com/infostreams/excel-merge/blob/master/Tasks/Worksheet.php

Once you're done, please create a pull request (GitHub will ask if you want to do this). It is then very easy to add your code to the repository, and you will automatically be included as a contributor in this repository. Thank you!

**Comment by mdanko2000** [comment]
Done.

**Comment by infostreams** [comment]
Thanks! I merged your code into the repository.
