### ISSUE TITLE
Question - Merging sheet content with the same name

### ISSUE THREAD

**Issue by emeraldjava** [infostreams/excel-merge#3]
Hi,

I came across this tool when I was working with https://github.com/PHPOffice/PhpSpreadsheet on an excel macro enabled file. In my case I need to populate the macro sheet with data, but I found the macro logic is getting stripped out when I write to the file.

In my case, i have a .xlsm file with ten sheets which contains macro logic. I have a second file with ten sheets which contains data. I was hoping to use the code below to merge the content of the two files

`$files = array("./admin/BHAA.Race.Master.xlsm",
     "/admin/clean-data-file.xlsx");
$merged = new ExcelMerge\ExcelMerge($files);
$merged->download("my-filename.xlsm");`

but what I am noticing is that the downloaded file contains 20 sheets. Could you advise how i might amend the existing code to merge the sheet content, such that i have ten sheets with data and macros. I'm happy to fork the repo and submit a push request but before I start I'd like to confirm this is in keeping with the vision you have for this tool.

Regards,
Paul

**Comment by infostreams** [comment]
Hi Paul,

Thanks for your feedback! First of all, it's been a year since I wrote this code and my memory of the exact details of the Excel format are a bit foggy. If I remember correctly, all the VBA code is contained within one single (binary) file, unlike the rest of contents of the XLSX file which is more or less a ZIP file with a bunch of XML inside. So I am curious: is all the VBA code actually present in the merged Excel file?

If that's the case, it means that the VBA code is indeed embedded independently from the sheets. This would be good news, because the changes you would need to make would be much simpler. 

I'm going to assume that the desired behavior is to overwrite a sheet if we come across one with an identical name. If you implement this I would prefer if you implement it by passing an array of options to the ExcelMerge class, for example

```php
$files = array("./admin/BHAA.Race.Master.xlsm", "/admin/clean-data-file.xlsx"); 
$options = array("overwrite" => true);
$merged = new ExcelMerge\ExcelMerge($files, $options); 
$merged->download("my-filename.xlsm");
```

The procedure itself is probably slightly involved, because the act of adding one sheet to an existing file has loads of side effects (it triggers changes in other XML files). So the best way of approaching it is (probably) to first loop through the files that are passed in, make a list of all worksheet names, keep track of which Excel file was the last one to have a sheet with that name, and then once you know a) which sheets there are and b) which Excel file you should get it from only THEN you start the merge. You go through your list of worksheet names and take one worksheet from here, the other from there, etc. You should probably start from an empty Excel file, though, and then proceed as described. Not sure how to obtain that empty Excel file, perhaps best to just pass it into the original array of files to be merged.

Anyway, that's how I'd approach it. I hope it makes sense and I hope I didn't miss anything (or have given you the wrong approach altogether). YMMW. Good luck! And let me know if it works out.

Cheers,
Ed

**Comment by infostreams** [comment]
Are you getting somewhere?

**Comment by emeraldjava** [comment]
Hi,
I tried locally and the basic merge works, but we keep seeing issues with the VBA macro code getting corrupted. For the moment, we've change approach and use an excel import sheet trick to merge the worksheet content outside of the php process.
Regards,
Paul
